nome = str(input('Digite Seu nome: ')).strip()
print ('Analisando seu nome... ')
print('Seu nome todo em maiúsculo: {}'.format(nome.upper()))
print('Seu nome todo em minúsculo: {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa[0])))